version: '3'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper_data:/data
    networks:
      - botnet

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "9900:9900"
    networks:
      - botnet
    extra_hosts:
      - host.docker.internal:host-gateway


  demo:
    build:
      context: ./services/demoservice-sayhelloworld
      dockerfile: Dockerfile
    container_name: demo-service
    ports:
      - "9901:9901"
    networks:
      - botnet
    extra_hosts:
      - host.docker.internal:host-gateway

  backstage:
    build:
      context: ./services/backstage-service
      dockerfile: Dockerfile
    container_name: backstage-service
    ports:
      - "9905:9905"
    networks:
      - botnet
    extra_hosts:
      - host.docker.internal:host-gateway

  gateway:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "9902:9902"
    networks:
      - botnet
    extra_hosts:
      - host.docker.internal:host-gateway

  group:
    build:
      context: ./services/grouputils-service
      dockerfile: Dockerfile
    container_name: grouputils-service
    ports:
      - "9906:9906"
    networks:
      - botnet
    extra_hosts:
      - host.docker.internal:host-gateway

  card:
    build:
      context: ./services/checkcard-service
      dockerfile: Dockerfile
    container_name: checkcard-service
    ports:
      - "9904:9904"
    networks:
      - botnet
    extra_hosts:
      - host.docker.internal:host-gateway


networks:
  botnet:

